In [1]:
import numpy as np

In [3]:
s1 = np.array([2,1,1])
s1a = np.array([2,1,1])
(s1 * s1a).sum()

6

In [4]:
s1 = np.array([2,1,1])
s1a = np.array([2,-1,1])
(s1 * s1a).sum()

4

In [6]:
s1 = -3.25 * np.array([2,1,1])
s2 = -3.25 * np.array([2,-1,1])
s3 = 3.5 * np.array([4,0,1])

print(s1)
print(s2)
print(s3)
s1+s2+s3


[-6.5  -3.25 -3.25]
[-6.5   3.25 -3.25]
[14.   0.   3.5]


array([ 1.,  0., -3.])